
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import Uiux from "./component/Uiux";

export const metadata = {
  manifest: "/manifest.json",
  metadataBase: new URL('http://localhost:3000'),
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph:{
    title:'공유시 1제목',
    description:'공유 요약 1정보',
    image:'/image/logo512.jpg'    
  },
  twitter: {
    title: 'Title webtsite',
    description: 'this is the desciption',
    image:'/image/logo512.jpg'
  },
  icons:{
    icon:'/image/favicon-16x16.png',
    apple:'/image/favicon-16x16.png',
    shortcut:'/image/logo512.jpg',
    other:{
      rel:'apple-touch-icon-precomposed',
      url: '/image/apple-touch-icon-57x57.png',
    }
  },
  keywords:['next','react','routing'],
  authors:[{name:'minkyu'}],
  robots:{
    index:false,
    follow:true,
    nocache:true,
    googlebot:{
      index:true,
      follow:false,
    }
  }
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Uiux>
          {children}

        </Uiux>
    
      </body>
    </html>
  );
}
